name: .NET

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: DarkNet

    runs-on: windows-latest

    steps:
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Clone repository
      uses: actions/checkout@v3.3.0
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build library
      run: dotnet build ${{ env.ProjectName }} --no-restore --configuration Release

    - name: Pack library
      run: dotnet pack ${{ env.ProjectName }} --no-build --configuration Release

    - name: Build Windows Forms demo
      run: msbuild darknet-demo-winforms -p:Configuration=Release -t:build -restore

    - name: Build WPF demo
      run: dotnet publish darknet-demo-wpf --no-restore --configuration Release -p:PublishSingleFile=true --runtime win-x64 --self-contained false

    - name: Flatten artifacts
      run: |
        mkdir upload
        copy ${{ env.ProjectName }}/bin/Release/*.*nupkg upload
        copy darknet-demo-winforms/bin/Release/*.exe upload
        copy darknet-demo-wpf/bin/Release/*/*/publish/*.exe upload

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.ProjectName }}
        path: upload
